In [0]:
import tensorflow as tf

In [0]:
hello=tf.constant('hello')

In [0]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [0]:
world=tf.constant('world')
type(hello+world)

tensorflow.python.framework.ops.Tensor

In [0]:
result=hello+world
result

<tf.Tensor 'add_1:0' shape=() dtype=string>

In [0]:
with tf.Session() as sess:
  result=sess.run(hello+world)           


In [0]:
a=tf.constant(2.0, tf.float32 )
b=tf.constant(3.0)
print(a, b)
result=a+b
print(result)

Tensor("Const_4:0", shape=(), dtype=float32) Tensor("Const_5:0", shape=(), dtype=float32)
Tensor("add_3:0", shape=(), dtype=float32)


In [0]:
with tf.Session() as sess:
   result=sess.run(a+b)

print(result)

  

5.0


In [0]:
a=tf.placeholder(tf.float32)
b=a*2
with tf.Session() as sess:
  result=sess.run(b, feed_dict={a:3.0})     

print(result)


6.0


In [0]:
const=tf.constant(10)
fill_mat=tf.fill((4,4), 10)
myzeros=tf.zeros((4,4))
myones=tf.ones((4,4))
myrandn=tf.random_normal((4,4), mean=0, stddev=1.0)
myrandu=tf.random_uniform((4,4), minval=0, maxval=1)
myzeros

<tf.Tensor 'zeros_1:0' shape=(4, 4) dtype=float32>

In [0]:
my_ops=[const, fill_mat, myzeros, myones, myrandn, myrandu]
sess=tf.InteractiveSession()

In [0]:
for op in my_ops:
   print(sess.run(op))
   print('\n') 


10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.33288014  0.26632178  0.69092906  0.5547271 ]
 [-0.82434255  0.87427473  0.53484994  1.3029914 ]
 [ 0.54399806  0.22724515 -0.23364513  0.1766407 ]
 [-0.15654604  0.45033866  1.3690883  -1.0601538 ]]


[[0.35795975 0.80641294 0.97362065 0.836256  ]
 [0.17651427 0.81097376 0.9499142  0.20056224]
 [0.9070728  0.83593965 0.46832502 0.09992349]
 [0.7696582  0.732106   0.5279672  0.67230296]]




In [0]:
import numpy as np
import tensorflow as tf

In [0]:
np.random.seed(101)
tf.set_random_seed(101)

In [0]:
rand_a=np.random.uniform(0, 100, (5,5))
rand_a


array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [0]:
rand_b=np.random.uniform(0, 100, (5,1))
rand_b


array([[99.43179012],
       [52.06653967],
       [57.87895355],
       [73.48190583],
       [54.19617722]])

In [0]:
a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)
add_op=a+b
mul_op=a*b
with tf.Session() as sess:
  add_result=sess.run(add_op, feed_dict={a:rand_a,b:rand_b})
  print(add_result)
  print('\n')
  mul_result=sess.run(mul_op, feed_dict={a:rand_a,b:rand_b})
  print(mul_result)
  print('\n')


[[151.07166  156.49855  102.27921  116.58396  167.95949 ]
 [135.45622   82.76316  141.42784  124.22093   71.06043 ]
 [113.30171   93.09215   76.06819  136.43912  154.42728 ]
 [ 96.71727   81.83804  133.83675  146.38118  101.10579 ]
 [122.72681  105.982925  59.044632  67.9831    72.89292 ]]


[[5134.644   5674.25     283.12433 1705.4707  6813.8315 ]
 [4341.8125  1598.267   4652.734   3756.8293   988.94635]
 [3207.8113  2038.1029  1052.7742  4546.9805  5588.1157 ]
 [1707.379    614.02527 4434.989   5356.7773  2029.8555 ]
 [3714.0984  2806.6438   262.76764  747.19855 1013.292  ]]




In [0]:
n_features=10
n_dense_neurons=3
x=tf.placeholder(tf.float32, (None, n_features))
w=tf.Variable(tf.random_normal([n_features, n_dense_neurons]))
b=tf.Variable(tf.ones([n_dense_neurons]))
xw=tf.matmul(x,w)


In [10]:
z=tf.add(xw,b)
a=tf.sigmoid(z)
init=tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  layer_out=sess.run(a, feed_dict={x:np.random.random([1, n_features])})
print(layer_out)

NameError: ignored